import React, { useState, useEffect } from "react";
import Nav from "../components/Nav";
import Head from "next/head";
import { destinations } from "../data.json";
function Destination() {
	const [activeContent, setActiveContent] = useState(destinations[0]);

	return (
		<div className="destination body">
			<Head>
				<title>Space Tourism Website</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Nav />
			<main
				id="main"
				className="grid-container grid-container--destination flow"
			>
				<h1 className="numbered-title">
					<span aria-hidden="true">01</span> Pick your destination{" "}
				</h1>
				<img src={activeContent.images.png} alt="the moon" />
				<div class="tab-list underline-indicators flex">
					<button
						onClick={() => {
							setActiveContent(destinations[0]);
						}}
						aria-selected={
							activeContent.name === destinations[0].name ? "true" : "false"
						}
						class="uppercase ff-sans-cond text-accent  letter-spacing-2"
					>
						Moon
					</button>
					<button
						onClick={() => {
							setActiveContent(destinations[1]);
						}}
						aria-selected={
							activeContent.name === destinations[1].name ? "true" : "false"
						}
						class="uppercase ff-sans-cond text-accent letter-spacing-2"
					>
						Mars
					</button>
					<button
						onClick={() => {
							setActiveContent(destinations[2]);
						}}
						aria-selected={
							activeContent.name === destinations[2].name ? "true" : "false"
						}
						class="uppercase ff-sans-cond text-accent letter-spacing-2"
					>
						Europa
					</button>
					<button
						onClick={() => {
							setActiveContent(destinations[3]);
						}}
						aria-selected={
							activeContent.name === destinations[3].name ? "true" : "false"
						}
						class="uppercase ff-sans-cond text-accent letter-spacing-2"
					>
						Titan
					</button>
				</div>
				<article className="destination-info flow">
					<h2 className="fs-800 uppercase ff-serif">{activeContent.name}</h2>
					<p>{activeContent.description}</p>
					<div className="destination-meta flex">
						<div>
							<h3 className="text-accent fs-200 uppercase">Avg. distance</h3>
							<p className=" ff-serif uppercase">{activeContent.distance}</p>
						</div>
						<div>
							<h3 className="text-accent fs-200 uppercase">Est. travel time</h3>
							<p className=" ff-serif uppercase">{activeContent.travel}</p>
						</div>
					</div>
				</article>
			</main>
		</div>
	);
}

export default Destination;
